name: tn_decoding
channels:
- conda-forge
- defaults
- edeno
dependencies:
- "python>=3.6"
- numpy
- numba
- scipy
- scikit-learn
- matplotlib
- loren_frank_data_processing
- replay_trajectory_classification
- ripple_detection
- xarray
- pandas
- dask
- tqdm
- statsmodels
- patsy
- jupyter
- jupyterlab
- nb_conda
- setuptools
- pytest
- pytest-cov
- coveralls
